### ISSUE TITLE
Using eleventyComputed writes result into template content

### ISSUE THREAD

**Issue by ryanccn** [noelforte/eleventy-plugin-vento#10]
When I try to do this in my templates:

```vto
eleventyComputed:
  title: Tagged “{{ tag }}”
```

It writes `Tagged “<the actual tag>”` to the `title` frontmatter entry but also replaces the template content with the result instead of the actual rendered template.

**Comment by ryanccn** [comment]
I think the same issue is also causing the permalink to replace the rendered content when `vto` is used as the Markdown template engine.

**Comment by noelforte** [comment]
Could be a caching issue, ran into similar problems with permalinks being injected into the template content. Will take a look later on to see what might be causing it. Thanks!

**Comment by noelforte** [comment]
@ryanccn I've opened some issues upstream to see if the cache behavior can be handled at a lower level. If not, I'll implement a patch to keep the cache cleared so things work as expected.

**Comment by ryanccn** [comment]
Thanks!
